name: Build

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_VERSION: 9.0.x

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore workloads
        working-directory: src
        run: dotnet workload restore
      - name: Restore dependencies
        run: dotnet restore src/jc-open-nov.sln
      - name: Build
        run: dotnet build src/jc-open-nov.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test src/jc-open-nov.sln --configuration Release --no-build
