on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_VERSION: 9.0.x

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore workloads
        working-directory: src
        run: dotnet workload restore
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build src/jc-open-nov.sln --configuration Release /p:Version=${VERSION}
      - name: Test
        run: dotnet test src/jc-open-nov.sln --configuration Release /p:Version=${VERSION} --no-build
      - name: Pack
        run: dotnet pack src/jc-open-nov.sln --configuration Release /p:Version=${VERSION} --output .
      - name: Push
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_APIKEY }}
